if(WIN32)
  set(HOME $ENV{USERPROFILE})
  string(REPLACE "\\" "/" HOME ${HOME})
else()
  set(HOME $ENV{HOME})
endif()
if(ENV{CMAKE_PREFIX_PATH})
  set(CMAKE_PREFIX_PATH "$ENV{CMAKE_PREFIX_PATH}")
else()
  set(CMAKE_PREFIX_PATH "${HOME}/local")
endif()

set(CMAKE_INSTALL_PREFIX "${HOME}/local")
set(NEXT_TOOLCHAIN "")
if(ENV{CMAKE_TOOLCHAIN_FILE})
  set(NEXT_TOOLCHAIN $ENV{CMAKE_TOOLCHAIN_FILE})
endif()

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  add_compile_options(-fcolor-diagnostics)
  string(FIND ${CMAKE_PREFIX_PATH} libc++ find_libcxx)
  if(NOT find_libcxx EQUAL -1)
    message(STATUS "Using libc++")
    set(CMAKE_INSTALL_PREFIX "${HOME}/local/lib.libc++")
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  add_compile_options(-fdiagnostics-color=always)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  add_compile_options(/diagnostics:caret)
  if(NOT NEXT_TOOLCHAIN)
    set(NEXT_TOOLCHAIN "$ENV{GH}/3rd-party/vcpkg/scripts/buildsystems/vcpkg.cmake")
  endif()
endif()

if(NEXT_TOOLCHAIN)
  include(${NEXT_TOOLCHAIN})
endif()