if(ENV{CMAKE_PREFIX_PATH})
  set(CMAKE_PREFIX_PATH $ENV{CMAKE_PREFIX_PATH})
else()
  set(CMAKE_PREFIX_PATH "$ENV{HOME}/local")
endif()
message(STATUS "Prefix: ${CMAKE_PREFIX_PATH}")

set(CMAKE_INSTALL_PREFIX "$ENV{HOME}/local")

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  add_compile_options(-fcolor-diagnostics)
  string(FIND ${CMAKE_PREFIX_PATH} libc++ find_libcxx)
  if(NOT find_libcxx EQUAL -1)
    message(STATUS "Using libc++")
    set(CMAKE_INSTALL_PREFIX "${ENV{HOME}}/local/lib.libc++")
  endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  add_compile_options(-fdiagnostics-color=always)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  add_compile_options(/diagnostics:caret)
endif()