#!/bin/zsh

cd $USERPROFILE
cmd.exe /c start "" xlaunch.exe -run .\\config.xlaunch &
echo "export DISPLAY=:0"
echo "export LIBGL_ALWAYS_INDIRECT=1"
# cmd.exe /c start "" xlaunch.exe -run "$(wslpath -w "$USERPROFILE/config.xlaunch")"
