#!/usr/bin/env zsh

if [ ${argv[(i)-p]} -le $#argv ] ; then
  cmd='pushd'
else
  cmd='cd'
fi

case "$1" in
  "")
    echo "aur [get, make, go, search]; -p = use pushd"
    ;;
  "go")
    if [ "$2" -ne "" ] ; then
      $cmd "$AUR/$2"
    else
      $cmd "$AUR"
    fi
    ;;
  "get")
    $cmd $AUR
    git clone "https://aur.archlinux.org/$2.git"
    cd "$2"
    echo "\n-> Got \e[0;34m$2\e[m."
    ;;
  "make")
    if [ "$2" -ne "" ] ; then
      $cmd "$AUR/$2"
    fi
    makepkg -is
    ;;
  "search")
    curl -sL "https://aur.archlinux.org/rpc/?v=5&type=search&arg=$2" | ~/bin/aurparse
    ;;
  *)
    echo "lolwat?"
    ;;
esac
